modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
[[mods]]
modId = "broomsmod"
version = "${file.jarVersion}"
displayName = "Brooms"
authors = "EterDelta, xbxbxb123"
description = '''
Adds balanced enchantable brooms to Minecraft. Fly around the world!
'''

[[dependencies.broomsmod]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.broomsmod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"
